# vim:fileencoding=utf-8:ft=conf

font_family Hack
font_size 11.0
disable_ligatures always
enabled_layouts tall:bias=50;full_size=1;mirrored=false, fat, stack
enable_audio_bell no

remember_window_size no
initial_window_width 100c
initial_window_height 35c

confirm_os_window_close 2
tab_bar_edge bottom
tab_bar_style powerline


