#:schema false
from_latest_tag = true
ignore_merge_commits = false
branch_whitelist = []
post_bump_hooks = [
  "cog changelog >! CHANGELOG.md"
]
pre_bump_hooks = []

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "dotfiles"
owner = "astutecat"
authors = [{ signature = "Will R", username = "astutecat" }]


[bump_profiles]
