# git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
[".zprezto"]
type = "git-repo"
url = "https://github.com/sorin-ionescu/prezto.git"
refreshPeriod = "672h"
[".zprezto".clone]
args = ["--recursive", "--depth", "1", "--quiet"]
[".zprezto".pull]
args = ["--recurse-submodules", "--quiet"]

