#!/bin/zsh

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source "${ZDOTDIR:-$HOME}/functions.zsh"
source "${ZDOTDIR:-$HOME}/aliases.zsh"
source "${ZDOTDIR:-$HOME}/variables.zsh"
source "${ZDOTDIR:-$HOME}/path.zsh"
source "${ZDOTDIR:-$HOME}/fzf-setup.zsh"

if [[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc" ]]; then
  source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"
fi

source "${ZDOTDIR:-$HOME}/completion.zsh"
if is_cmd fastfetch; then
  fastfetch
elif is_cmd neofetch; then
  neofetch --config "$HOME/.config/neofetch/config.conf"
fi
