#!/bin/zsh

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source "${ZDOTDIR:-$HOME}/functions.zsh"
source "${ZDOTDIR:-$HOME}/variables.zsh"
source "${ZDOTDIR:-$HOME}/path.zsh"
source "${ZDOTDIR:-$HOME}/fzf-setup.zsh"
source "${ZDOTDIR:-$HOME}/aliases.zsh"

if [[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc" ]]; then
  source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"
fi

source "${ZDOTDIR:-$HOME}/completion.zsh"

# Execute code only if STDERR is bound to a TTY.
if [[ -o INTERACTIVE && -t 2 ]]; then
  if is_cmd fastfetch; then
    fastfetch
  fi
  # Print a random, hopefully interesting, adage.
  if (( $+commands[fortune] )); then
    fortune -s ~/.local/share/fortunes/
  fi
fi >&2
