let g:WhiplashProjectsDir = "~/dev/"
let g:ale_completion_enabled = 1
let g:ale_sign_column_always = 1
let g:ale_set_balloons = 1
let g:ale_completion_delay = 1000
let g:ale_sign_error = '●'
let g:ale_sign_warning = '.'
let g:lsp_document_code_action_signs_enabled = 0
let g:lsp_completion_documentation_enabled = 0
let g:ale_hover_cursor = 0
let g:ale_completion_autoimport = 1
set omnifunc=ale#completion#OmniFunc
