# vim:ft=toml.chezmoitmpl
[".config/emacs"]
type = "git-repo"
url = "https://github.com/doomemacs/doomemacs"
refreshPeriod = "672h"
[".config/emacs".clone]
args = ["--depth", "1", "--quiet"]
[".config/emacs".pull]
args = ["--quiet"]


{{ if not .is_macos }}
[".local/bin/git-squash"]
  type = "file"
  url = "https://raw.githubusercontent.com/sheerun/git-squash/master/git-squash"
  refreshPeriod = "672h"
  executable = true
{{ end }}
