# vim:ft=toml.chezmoitmpl

[settings]
experimental = false
cache_prune_age = "14d"
disable_hints = [ "python_multi", "python_precompiled" ]

[tools]
"cargo:cargo-cache" = "latest"
"cargo:du-dust" = "latest"
pre-commit = "latest"
adr-tools = "latest"
go = "1.21.1"
lua = "latest"
chezmoi = "latest"
dotnet = "latest"
elixir = "latest"
erlang = "latest"
"cargo:cargo-binstall" = "latest"
