theme = 'onedark'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
line-number = "relative"
color-modes = true
trim-trailing-whitespace = true

[editor.statusline]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# [editor.whitespace.render]
# space="all"
# tab="all"

[editor.indent-guides]
render = true
skip-levels = 1
